---
# Handlers for Cloudera Manager Server.

#- set_fact:
#    scm_hostname={{ hostvars[groups['tag_scm_server'][0]]['inventory_hostname'] }}
#  with_items: "{{ groups['tag_scm_server'] }}"




- name: restart cloudera-scm-server
  service: name=cloudera-scm-server state=restarted
#  notify:
#    - wait cloudera-scm-server


#{{ hostvars[groups['tag_krb5_server'][0]]['inventory_hostname'] }}


- pause:
    minutes: 1

#- name: wait cloudera-scm-server
#  wait_for:
#    host= {{ hostvars[groups['tag_scm_server'][0]]['inventory_hostname'] }}
#    port={{ scm_port }}
#    delay=5
#    state=started
#    timeout=300
