---
# https://cloudera.github.io/cm_api/docs/python-client/

- name: Install Python PIP
  yum: name=python-pip state=latest update_cache=yes

#- name: update pip
#  shell: "pip install --upgrade pip"
- name:  upgrade pip
  pip: 
    name: pip
    state: latest


- name: Install CM Python API Client
  pip: name=cm-api


